### ISSUE TITLE
CME when piping into chest from 2 separate TE's

### ISSUE THREAD

**Issue by oitsjustjose** [CharsetMC/Charset#2]
I'm probably **begging** to get yelled at... but I compiled a build of Charset after your massive commit today, and [ran into this crash](http://pastebin.com/CSQ6Mggi) when piping items out of my two separate tile entities (a cobblegen and smooth stone generator) into the _same_ chest.

**Comment by asiekierka** [comment]
That's *good*. CharsetPipes is not at all tested.

**Comment by asiekierka** [comment]
Temporary fix applied; better fix will be written in a few days.

**Comment by nabijaczleweli** [comment]
"better fix will be written someday" a.k.a. there'll never be a different piece of code thereinplace.

**Comment by asiekierka** [comment]
Yes!

**Comment by asiekierka** [comment]
Yes, that.

**Comment by exaskye** [comment]
It's now 2017 and the temp fix is still in use. :P

> There's nothing more permanent than a temporary fix that works.

**Comment by asiekierka** [comment]
@unascribed Honestly, https://github.com/CharsetMC/Charset/issues/6 is a much worse bug from 2015 that I still haven't properly fixed.

**Comment by exaskye** [comment]
@asiekierka Ehh, that's dropping items on the floor, which people are used to from Buildcraft. This issue is/was a crash.

**Comment by asiekierka** [comment]
@unascribed I'm not even sure if the fix is temporary anymore, seeing as that part has been rewritten again and again in 2016... might as well close it.
