### ISSUE TITLE
Backpack Differences (issues and suggestions)

### ISSUE THREAD

**Issue by copygirl** [CharsetMC/Charset#42]
I thought I'd just make an issue on all the backpack issues or differences from BetterStorage that I'd like you to address eventually / take a look at / get a response for.
#### Issues / Todo
- [x] Backpack renders too small in inventory.
- [ ] Bounding box is not dependent on orientation.
- [ ] Backpack is instantly equipped. (Equipping should be faster than breaking though.)
- [ ] Can't open other players' backpacks. (Should include config setting to disable for servers that can't trust players and don't want items being stolen.)
- [ ] No lid animation.
- [x] No opening sound. (BS used low-pitched snow step sound.)
#### Differences
- [ ] Crafting recipe: Is there a reason for the difference? In my opinion, BS' recipe nailed it. I thought of the wool as the padding. Current recipe feels very "pick some items that somewhat fit but not really" - also isn't the Tinkers knapsack similar?
- [ ] BetterStorage backpacks functioned as armor, similar to leather with increased durability.
- [ ] Another feature was that [protection enchantments worked similar to unbreaking](https://github.com/copygirl/BetterStorage/blob/master/src/main/java/net/mcft/copy/betterstorage/item/ItemBackpack.java#L247-L281).
- [ ] In BetterStorage, mobs rarely (~0.1%) spawned with backpacks with [random early game loot](https://github.com/copygirl/BetterStorage/blob/master/src/main/java/net/mcft/copy/betterstorage/misc/handlers/BackpackHandler.java#L69-L115), sometimes dungeon loot.
- [ ] Special backpacks with usually unobtainable enchantments as [dungeon loot](https://github.com/copygirl/BetterStorage/blob/master/src/main/java/net/mcft/copy/betterstorage/misc/DungeonLoot.java#L45-L57)?
- [ ] Friendly Endermen / ender backpack?
- [ ] Config setting for controlling backpack size (1 to 6 rows) and whether it takes up the chestplate slot. This allows the backpack to be useful in any modpack, regardless of target audience, difficulty or gimmicks (imagine one in space, where you have to wear a spacesuit or else you'd die).

I'll update the list as I remember other stuff or come across new issues. I won't include totally new content suggestions in this since it's a bit early for that, though I've already shared some with you.

**Comment by asiekierka** [comment]
>Is there a reason for the difference?

The wool should be back, yes - however, I think of the sticks as the bits which make the backpack nice, solid and rigid. Also, there should be a chest in the recipe.

>BetterStorage backpacks functioned as armor, similar to leather with increased durability.

Slightly problematic as I extend ItemBlock and cannot also extend ItemArmor.

>and whether it takes up the chestplate slot

Implementation complexity makes this a really low priority thing.

**Comment by copygirl** [comment]
> Slightly problematic as I extend ItemBlock and cannot also extend ItemArmor.

It doesn't have to be ItemBlock to be placeable as a block on right-click.

> Implementation complexity makes this a really low priority thing.

WearableBackpacks API was designed in such a way that this was trivial.

**Comment by SoniEx2** [comment]
Why doesn't forge have IItemArmor again?

**Comment by asiekierka** [comment]
Well, things have changed.
