### ISSUE TITLE
Redstone State Update Failure

### ISSUE THREAD

**Issue by fredo121** [CharsetMC/Charset#47]
In the image below you can see that the state of the redstone cable was not updated according to the given logic. I have switched the lever in the center from off to on which has turned off the redstone torch on the block it's attached to leading to the whole cable being in the off state. 
Normally the whole cable should have stayed in the on state because the two other redstone torches are still on.  
<img width="628" alt="charsetfailure" src="https://cloud.githubusercontent.com/assets/13404035/12596208/243af454-c47f-11e5-98ec-35a7bfac1c4a.PNG">

**Comment by asiekierka** [comment]
I *finally* managed to reproduce this.

**Comment by asiekierka** [comment]
Wires have been removed as of 0.3.1.
