### ISSUE TITLE
Almost-full inventories will drop non-inserted part of stack on insertion attempt.

### ISSUE THREAD

**Issue by oitsjustjose** [CharsetMC/Charset#6]
Rather hard to _explain_ this one, but I'll try:

I have an inventory (A hopper, for example), and it's completely full. Stuffed. No room. I send it more items via a Pipe, and boom, instead of jamming the pipe, the item gets inserted into the hopper.... but where? Hopper does not receive new items, and the ItemStack does not spawn in the world.. so voided? This bug isn't specific to hoppers, it happens with all of CrissCross's TileEntities too, and I checked to see if it was a bug in their code, but when using a hopper to insert into their inventory, the items don't get voided.

**Keep up the good work**
:cookie:

**Comment by asiekierka** [comment]
Fixed the voiding part of it. Handling the rest of the issue depends entirely on whether I even want per-stack transfer, which I'm still thinking about.
