### ISSUE TITLE
Disabled sides on gates not recognized after rotation

### ISSUE THREAD

**Issue by ruyanve** [CharsetMC/Charset#65]
Whenever I disable a side of any gate and rotate the gate, the disabled side is not recognized as disabled and needs to be enabled and disabled again to be recognized.

![gate1](https://cloud.githubusercontent.com/assets/7439516/15453089/95e3f3b0-2007-11e6-9ca2-8342cabf2342.jpg)

edit: well now it looks like disabling a side does nothing at all... I may just need a good sleep, I could swear that worked before! Damn!

**Comment by ruyanve** [comment]
Oh, forgot to mention... I am still on Charset-0.3.0-test-i64

woops

**Comment by asiekierka** [comment]
No whoops necessary, but that /is/ odd. I'll look into it.

2016-05-22 10:28 GMT+02:00 ruyanve <notifications@github.com>:

**Comment by asiekierka** [comment]
Works fine on my latest in-dev build. The one I sent you might've been during gate refactors, let me deliver one to you...

**Comment by asiekierka** [comment]
http://asie.pl/Charset-0.3.0-test-i65.jar

**Comment by ruyanve** [comment]
Cheers Asie!

Did some testing and feel even more stupid now! With the wrench instead of the screwdriver I can't disable any inputs at all. On right and shift+right click all it does is rotate the gate. (clock and counter clockwise).

Also, it feels kind of awkward to click on the gates with a wrench, with the screwdriver I had a better feeling of what I am clicking at. That sounds weird but I felt like telling anyway.

**Comment by asiekierka** [comment]
Don't use the wrench. In the latest *latest* version, just shift-click with an empty hand. The wrench is *only* for rotating things.

**Comment by ruyanve** [comment]
Derp... Works like a charm now!
Rotating and disabling!

Thank you!
