### ISSUE TITLE
Request: The One Probe integration for gates

### ISSUE THREAD

**Issue by ruyanve** [CharsetMC/Charset#66]
I'm really into McJtys The one Probe mod and would love to see some integration if possible!
Any chances you'll have a look at his API and maybe give us some sleek info on what we are looking at? :-)

https://github.com/McJty/TheOneProbe/tree/master/src/main/java/mcjty/theoneprobe/api

**Comment by asiekierka** [comment]
I'm not sure what such integration would involve.

**Comment by ruyanve** [comment]
Well, anything better than this would be a great start... :-P

![gate2](https://cloud.githubusercontent.com/assets/7439516/15456615/091d7702-2076-11e6-9fb9-2658ce6fefc4.jpg)

And maybe I am going at this in the wrong direction and I should bother McJty instead of you?
Anyway, here's what I mean...
What I always run into is that I build in very compact ways and often have to remove stuff to only check on a gate state, because wires and stuff block the part of it. I don't think even Waila got that one, but maybe there's a way?

The overlay that came with Waila for PR gates was always nice for people on the server and if you ever plan on adding simple timer gates (also nice for redstone newbs on the server!), the timer settings would also be helpful to see.

Stuff like that... you're the creative one here :-P

**Comment by asiekierka** [comment]
tile.null.name and tile.null are direct results of no MCMultiPart integration. Report to McJty, as MCMultiPart is entering Forge right now - it's a pull request.

The overlay was nice and I'd love to see an addon reimplementing it (ask tterrag on WAILAPlugins?), but I'm afraid I'm more interested in making the textures better (right now they're placeholders from RedLogic).

>you're the creative one here

Hahaha, no.

**Comment by ruyanve** [comment]
Cheers mate,

saw Amadornes tweeting about it. Exciting! I'm out of the loop with most of the MC stuff for a while now, but I hope Lex has become a bit more relaxed (the last run-in I had with him resulted in me being baaned from his twitter for a week :-D).

Anyways, thank you again for your effords, I'll report to tterrag and mcjty about the other stuff. 
dobrej nocy

**Comment by asiekierka** [comment]
>for a week

I've been banned for 16 months and counting, despite him promising to unban me 15 months ago. Ah well - can't be helped.

**Comment by ruyanve** [comment]
Oh yeah... wasn't that along the Nova stuff that went down?
Good times... ;-)
