### ISSUE TITLE
Charset blocks from "+" and "|" have no particle texture

### ISSUE THREAD

**Issue by MRebhan** [CharsetMC/Charset#67]
When you break a pipe, it shows missing texture particles and when you break the redstone wires, they do not seem to create any particles.

Pictures: http://imgur.com/a/Ku0x3

This results in https://github.com/mezz/JustEnoughItems/issues/283 (Unability to use color search with these two charset mods)

This does not affect the logic gates.

**Comment by asiekierka** [comment]
I am aware. 0.3.0-pre is heavily in development.

**Comment by asiekierka** [comment]
Moving from MCMP1 to MCMP2 should, by extension, fix this bug.
