### ISSUE TITLE
Relicense to Apache License 2.0

### ISSUE THREAD

**Issue by asiekierka** [CharsetMC/Charset#68]
The Apache License is a bit better protected against abuse/misuse than the MIT, and will probably be fit better for a growing project like Charset.

License: https://www.apache.org/licenses/LICENSE-2.0

Contributors so far:

@blay09 
@rubensworks 
@SoniEx2 

Please respond with something along the lines of: "I agree to license all my contributions to Charset under the terms of the Apache License, version 2.0."

(This should go a bit easier than BuildCraft.)

**Comment by rubensworks** [comment]
I agree to license all my contributions to Charset under the terms of the Apache License, version 2.0.

**Comment by blay09** [comment]
I agree to license all my contributions to Charset under the terms of the Apache License, version 2.0.

**Comment by skyem123** [comment]
(Quick question, aren't you allowed to mix Apache licensed code and MIT licensed code? :P)

**Comment by asiekierka** [comment]
(I am, but why not have one license to rule them all for the Charset code?)

**Comment by SoniEx2** [comment]
I agree to license my CODE REMOVAL... wait... can you even license code removal????

**Comment by asiekierka** [comment]
Better safe than sorry.

**Comment by SoniEx2** [comment]
I agree to license all my contributions to Charset under the terms of the Apache License, version 2.0, as long as the following line gets added to the NOTICE file.

```
SoniEx2 was here.
```

**Comment by asiekierka** [comment]
@SoniEx2 

what

no

**Comment by SoniEx2** [comment]
@asiekierka Your fault for choosing a dumb license.

**Comment by asiekierka** [comment]
@SoniEx2 I'll just revert your commit

**Comment by SoniEx2** [comment]
I just want charset to stay MIT :(

**Comment by asiekierka** [comment]
@SoniEx2 it's not MIT right now because none of the contributions are MIT

**Comment by SoniEx2** [comment]
I don't like the apache license 2.0, any other option?

**Comment by GirafiStudios** [comment]
@SoniEx2 , you really want to start complaining about the license? You have removed 1 freaking line...

**Comment by SoniEx2** [comment]
@GirafiStudios this isn't about MY contributions, this is about my ability to reuse charset code.

**Comment by gjgfuj** [comment]
And why can't you? Apache is plenty reusable.

**Comment by SoniEx2** [comment]
Not with GPLv2, not with MIT

**Comment by asiekierka** [comment]
Not even the MIT is reuseable with the MIT - you legally need to include every MIT license header from every project whose code you incorporate (which is why Charset distributes three MIT license files).

**Comment by nabijaczleweli** [comment]
Can we relicense to WTFPL instead? :v

**Comment by asiekierka** [comment]
I like my licenses slightly more serious

2016-05-24 0:32 GMT+02:00 Jędrzej <notifications@github.com>:

**Comment by nabijaczleweli** [comment]
Why not [pubdom](http://choosealicense.com/licenses/#unlicense) it then, eh

**Comment by SoniEx2** [comment]
Well, BSL is reusable with BSL and MIT...

**Comment by gjgfuj** [comment]
apache is usable with GPLv3?

**Comment by SoniEx2** [comment]
I did say GPLv2, not GPLv2+

**Comment by gjgfuj** [comment]
yes, but why gplv2 over gplv3?

**Comment by asiekierka** [comment]
No Tivoization clause, usually, which is only useful if you're a hardware manufacturer.

**Comment by asiekierka** [comment]
https://github.com/CharsetMC/Charset/commit/fd6af043bad6315e28c75b110d0a8ae69ad9940f
